/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jgranados.ipc1_2026.poo.avanzados.threads.swing;

import com.jgranados.ipc1_2026.poo.avanzados.threads.Articulo;
import java.util.Random;

/**
 *
 * @author jose
 */
public class PanelCajero extends javax.swing.JPanel implements Runnable {
    
    private Articulo[] articulos;

    /**
     * Creates new form PanelCajero
     */
    public PanelCajero(String nombre, int cantidad) {
        initComponents();
        articulos = new Articulo[cantidad];
        Random random =new Random();
        for (int i = 0; i < articulos.length; i++) {
            articulos[i] = new Articulo("a" + i, random.nextInt(1, 6));
        }
        lblNombre.setText(nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            procesarArticulos(articulos);
            lblInfo.setText("--");
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }
    }
    
    private void procesarArticulos(Articulo[] articulos) throws InterruptedException {
        for (int i = 0; i < articulos.length; i++) {
            Articulo articulo = articulos[i];
            lblInfo.setText(articulo.getNombre());
            Thread.sleep(articulo.getPeso() * 1000);
        }
    }
}
