/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jgranados.ipc1_2026.poo.swing.totito.frontend;

import com.jgranados.ipc1_2026.poo.swing.totito.backend.MotorTotito;
import com.jgranados.ipc1_2026.poo.swing.totito.backend.exceptions.CasillaMarcadaException;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class TotitoFrame extends javax.swing.JFrame {
    
    private static final String PATH_CIRCLE = "/images/totito/icons8-circle-96.png";
    private static final String PATH_CROSS = "/images/totito/icons8-cross-96.png";

    private MotorTotito motorTotito = new MotorTotito();

    /**
     * Creates new form TotitoFrame
     */
    public TotitoFrame() {
        initComponents();
        this.pnlInicio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCasilla00 = new javax.swing.JLabel();
        lblCasilla10 = new javax.swing.JLabel();
        lblCasilla21 = new javax.swing.JLabel();
        lblCasilla01 = new javax.swing.JLabel();
        lblCasilla11 = new javax.swing.JLabel();
        lblCasilla22 = new javax.swing.JLabel();
        lblCasilla02 = new javax.swing.JLabel();
        lblCasilla20 = new javax.swing.JLabel();
        lblCasilla12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        pnlInicio = new javax.swing.JPanel();
        txtJugador1 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        btnJuegoNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCasilla00.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        lblCasilla00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasilla00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCasilla00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasilla00MouseClicked(evt);
            }
        });

        lblCasilla10.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        lblCasilla10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasilla10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCasilla10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasilla10MouseClicked(evt);
            }
        });

        lblCasilla21.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        lblCasilla21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasilla21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCasilla21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasilla21MouseClicked(evt);
            }
        });

        lblCasilla01.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        lblCasilla01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasilla01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCasilla01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasilla01MouseClicked(evt);
            }
        });

        lblCasilla11.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        lblCasilla11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasilla11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCasilla11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasilla11MouseClicked(evt);
            }
        });

        lblCasilla22.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        lblCasilla22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasilla22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCasilla22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasilla22MouseClicked(evt);
            }
        });

        lblCasilla02.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        lblCasilla02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasilla02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCasilla02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasilla02MouseClicked(evt);
            }
        });

        lblCasilla20.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        lblCasilla20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasilla20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCasilla20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasilla20MouseClicked(evt);
            }
        });

        lblCasilla12.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        lblCasilla12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCasilla12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCasilla12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCasilla12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCasilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCasilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCasilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCasilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCasilla00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCasilla01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCasilla02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCasilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCasilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCasilla00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCasilla01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCasilla02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCasilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCasilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCasilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCasilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCasilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCasilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJugador2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pnlInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJugador1)
                    .addComponent(txtJugador2)
                    .addGroup(pnlInicioLayout.createSequentialGroup()
                        .addComponent(btnIniciar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnJuegoNuevo.setText("Juego nuevo");
        btnJuegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnJuegoNuevo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnJuegoNuevo)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJuegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoNuevoActionPerformed
        this.pnlInicio.setVisible(true);
        reiniciarJuego();
    }//GEN-LAST:event_btnJuegoNuevoActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        motorTotito.registrarJugadores(txtJugador1.getText(), txtJugador2.getText());
        this.lblJugador1.setText(txtJugador1.getText());
        this.lblJugador2.setText(txtJugador2.getText());
        this.pnlInicio.setVisible(false);
        resaltarJugadorEnTurno();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void lblCasilla00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasilla00MouseClicked
        registrarMarca(0, 0, lblCasilla00);
    }//GEN-LAST:event_lblCasilla00MouseClicked

    private void lblCasilla10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasilla10MouseClicked
        registrarMarca(1, 0, lblCasilla10);
    }//GEN-LAST:event_lblCasilla10MouseClicked

    private void lblCasilla20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasilla20MouseClicked
        registrarMarca(2, 0, lblCasilla20);
    }//GEN-LAST:event_lblCasilla20MouseClicked

    private void lblCasilla01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasilla01MouseClicked
        registrarMarca(0, 1, lblCasilla01);
    }//GEN-LAST:event_lblCasilla01MouseClicked

    private void lblCasilla11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasilla11MouseClicked
        registrarMarca(1, 1, lblCasilla11);
    }//GEN-LAST:event_lblCasilla11MouseClicked

    private void lblCasilla21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasilla21MouseClicked
        registrarMarca(2, 1, lblCasilla21);
    }//GEN-LAST:event_lblCasilla21MouseClicked

    private void lblCasilla02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasilla02MouseClicked
        registrarMarca(0, 2, lblCasilla02);
    }//GEN-LAST:event_lblCasilla02MouseClicked

    private void lblCasilla12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasilla12MouseClicked
        registrarMarca(1, 2, lblCasilla12);
    }//GEN-LAST:event_lblCasilla12MouseClicked

    private void lblCasilla22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCasilla22MouseClicked
        registrarMarca(2, 2, lblCasilla22);
    }//GEN-LAST:event_lblCasilla22MouseClicked

    private void registrarMarca(int fila, int columna, JLabel etiqueta) {
        try {
            motorTotito.marcarCasilla(fila, columna);

            if (motorTotito.obtenerJugadorEnTurno().getMarca() == 1) {
                etiqueta.setIcon(new ImageIcon(getClass().getResource(PATH_CIRCLE)));
            } else {
                etiqueta.setIcon(new ImageIcon(getClass().getResource(PATH_CROSS)));
            }
            
            if (motorTotito.hayGanador()) {
                indicarGanador();
            } else {
                resaltarJugadorEnTurno();
            }
            
            
        } catch (CasillaMarcadaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void indicarGanador() {
        JOptionPane.showMessageDialog(this, "El jugador " + motorTotito.obtenerJugadorEnTurno().getNombre() + " ya gan[o", "Listo", JOptionPane.INFORMATION_MESSAGE);
    }

    private void resaltarJugadorEnTurno() {
        lblJugador1.setForeground(Color.BLACK);
        lblJugador2.setForeground(Color.BLACK);

        if (motorTotito.esTurnoDeUno()) {
            lblJugador1.setForeground(Color.BLUE);
        } else {
            lblJugador2.setForeground(Color.BLUE);
        }
    }

    private void reiniciarJuego() {
        this.txtJugador1.setText("");
        this.txtJugador2.setText("");
        motorTotito.reiniciarJuego();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnJuegoNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCasilla00;
    private javax.swing.JLabel lblCasilla01;
    private javax.swing.JLabel lblCasilla02;
    private javax.swing.JLabel lblCasilla10;
    private javax.swing.JLabel lblCasilla11;
    private javax.swing.JLabel lblCasilla12;
    private javax.swing.JLabel lblCasilla20;
    private javax.swing.JLabel lblCasilla21;
    private javax.swing.JLabel lblCasilla22;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables

}
